# Мы импортируем вспомогательные инструменты для типов.
# Pylance понимает этот импорт, но в саму игру он не попадет.
from typing import TypeVar, Generic, Iterator, Literal, TypeAlias, Optional, Tuple, List

# Объявляем переменные типа (шаблоны)
_T = TypeVar("_T")
_T_co = TypeVar("_T_co", covariant=True)
_KT = TypeVar("_KT")
_VT = TypeVar("_VT")

# === ЧАСТЬ 1: ФУНДАМЕНТ PYTHON ===

class object:
    def __init__(self) -> None: ...

class type: ...

class NoneType:
    def __bool__(self) -> bool: ...

# --- Базовые типы ---

# Числа
class int:
    def __add__(self, other: object) -> int: ...
    def __sub__(self, other: object) -> int: ...
    def __mul__(self, other: object) -> int: ...
    def __truediv__(self, other: object) -> float: ...
    def __floordiv__(self, other: object) -> int: ...
    def __mod__(self, other: object) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __abs__(self) -> int: ...
    def __hash__(self) -> int: ...

class float:
    def __add__(self, other: object) -> float: ...
    def __sub__(self, other: object) -> float: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...

class bool(int): ...

class str:
    def __add__(self, other: object) -> str: ...
    def format(self, *args: object, **kwargs: object) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# --- Коллекции (Generic) ---

# Добавляем Generic[_T], чтобы работало list[int]
class list(Generic[_T]):
    def append(self, item: _T) -> None: ...
    def pop(self, index: int = -1) -> _T: ...
    def remove(self, item: _T) -> None: ...
    def __len__(self) -> int: ...
    # Iterator позволяет делать "for x in list" с правильным типом x
    def __iter__(self) -> Iterator[_T]: ...
    def __getitem__(self, index: int) -> _T: ...
    def __setitem__(self, index: int, value: _T) -> None: ...

# Добавляем Generic[_T_co], чтобы работало tuple[int, int]
# Pylance обрабатывает tuple магически, но Generic нужен для синтаксиса []
class tuple(Generic[_T_co]):
    def __ne__(self, other: object) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T_co]: ...
    def __getitem__(self, index: int) -> _T_co: ...

# Добавляем set
class set(Generic[_T]):
    def add(self, item: _T) -> None: ...
    def remove(self, item: _T) -> None: ...
    def __contains__(self, item: object) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...

class dict(Generic[_KT, _VT]):
    def get(self, key: _KT, default: object = None) -> _VT: ...
    def __getitem__(self, key: _KT) -> _VT: ...
    def __setitem__(self, key: _KT, value: _VT) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def items(self) -> Iterator[tuple[_KT, _VT]]: ...
    def keys(self) -> Iterator[_KT]: ...
    def values(self) -> Iterator[_VT]: ...

class range:
    def __iter__(self) -> Iterator[int]: ...

# --- Глобальные функции ---
def len(obj: object) -> int: ...
def print(*args: object) -> None: ...
def abs(x: object) -> int: ...
def min(a: object, b: object) -> int: ...
def max(a: object, b: object) -> int: ...

# --- TYPE ALIASES ---
# Определяем Vector2 как кортеж из двух целых чисел
Vector2 = Tuple[int, int]
# Определяем путь как список таких векторов
Path = List[Vector2]

# === ЧАСТЬ 2: API ИГРЫ ===

# 1. Создаем "Призрачный тип" для всех направлений
# Он нужен только для того, чтобы объединить константы в одну группу
class _DirectionObject:
    # Явно разрешаем сравнение (eq)
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    # Разрешаем использование в качестве ключей словаря/множества
    def __hash__(self) -> int: ...

# 2. Объявляем North, East... как ЭКЗЕМПЛЯРЫ этого типа
# Теперь для анализатора они "одного поля ягоды" и их можно сравнивать
North: _DirectionObject
East: _DirectionObject
South: _DirectionObject
West: _DirectionObject

# 3. Общий тип (принимает и наши объекты, и числа 0-3)
Direction: TypeAlias = _DirectionObject | int

class Items:
    # Теперь анализатор знает точное значение
    Water: Literal["Water"]
    Wood: Literal["Wood"]
    Hay: Literal["Hay"]
    Power: Literal["Power"]
    Cactus: Literal["Cactus"]
    Pumpkin: Literal["Pumpkin"]
    Carrot: Literal["Carrot"]
    Fertilizer: Literal["Fertilizer"]

# Группируем их в один тип для удобства аргументов функций
ItemType: TypeAlias = Literal[
    "Water",
    "Wood",
    "Hay",
    "Power",
    "Cactus",
    "Pumpkin",
]

class Entities:
    Pumpkin: Literal["Pumpkin"]
    Grass: Literal["Grass"]
    Bush: Literal["Bush"]
    Tree: Literal["Tree"]
    Carrot: Literal["Carrot"]
    Sunflower: Literal["Sunflower"]
    Hedge: Literal["Hedge"]
    Treasure: Literal["Treasure"]
    Cactus: Literal["Cactus"]

EntityType: TypeAlias = Literal[
    "Pumpkin",
    "Grass",
    "Bush",
    "Tree",
    "Carrot",
    "Sunflower",
    "Hedge",
    "Treasure",
    "Cactus",
]

class Grounds:
    Soil: Literal["Soil"]
    Turf: Literal["Turf"]
    Grassland: Literal["Grassland"]

GroundType: TypeAlias = Literal["Soil", "Turf", "Grassland"]

class Hats:
    Brown_Hat: Literal["Brown_Hat"]
    Dinosaur_Hat: Literal["Dinosaur_Hat"]

HatType: TypeAlias = Literal["Brown_Hat", "Dinosaur_Hat"]

# Функции игры
# Используем object для direction, чтобы принимать и классы, и int
def change_hat(h: HatType) -> None: ...
def clear() -> None: ...
def measure(d: Optional[Direction] = None) -> Vector2: ...
def move(d: Direction) -> bool: ...
def swap(d: Direction) -> None: ...
def get_companion() -> Optional[Tuple[EntityType, Vector2]]: ...
def turn(direction: object) -> None: ...
def get_pos_x() -> int: ...
def get_pos_y() -> int: ...
def get_world_size() -> int: ...
def get_ground_type() -> str: ...
def get_entity_type() -> Optional[str]: ...
def till() -> None: ...
def plant(entity: object) -> None: ...
def harvest() -> None: ...
def use_item(item: object) -> None: ...
def can_harvest() -> bool: ...
def quick_print(msg: object) -> None: ...
def get_water() -> float: ...
def num_items(item: object) -> int: ...
def get_time() -> float: ...
